name: student-api-config-pipeline
on:
  push:
    tags:
      - STUDENT-API-PLAY-CONFIG-*
    paths:
      - student_service/config-deploy/**"

jobs:
  student-api-config-play-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@master

      - name: Install botocore and boto3
        run: pip install botocore boto3

      - name: Get the latest terraform version
        run: make terraform-install

      - name: Apply terraform student-api config
        run: make terraform-apply
        working-directory: student_service/config-deploy/
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Configs for student_service secrets
        run: make ansible-apply
        working-directory: student_service/config-deploy/
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: vault_env
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ENVIRONMENT: play
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
